spring.application.name=BE

spring.data.mongodb.uri=mongodb://localhost:27017/gradora
spring.data.mongodb.database=gradora

app.jwt.secret=5ppKhkpVKWGg8tikuIVM/gHri6lUrkUWXzKdECG4nVEI/P954P7CIOJhYL2nxRm5d6Cle/0rQ2JgXiod6BH9TQ==
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=2592000000

app.webhook.secret=gradora-webhook-secret-change-in-prod
app.payment.base-url=http://localhost:8080
